In [3]:
class Employee:#Employee class
    empCount=0 ##employeeConut is used to keep track of numner of employee objects
    salSum=0 #salSum is used to take the average of the salaries of the Employee object 
    def __init__(self,name,family,salary,department): #constructor for Employee as per the requirements
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1
        Employee.salSum+=self.salary
    def avg(self):
        return Employee.salSum/Employee.empCount
    def displayCount(self): #One of the functions in Employee class
        print ("Total Employee %d" % Employee.empCount)
    def displayEmployee(self):#another function for employee class
        print("Name : ", self.name, "Family: ", self.family , "Salary: ", self.salary, "department:",self.department)

emp1 = Employee("Ravi","Kumar",2000,"software")#Employee objects creation with intialization
emp2 = Employee("Sunil","Naidu",5000,"starbucks")
print("avg:",emp2.avg())#calling average function
class FulltimeEmployee(Employee):#FulltimeEmployee class with Employee as its parent class
    def __init__(self,name,family,salary,department,c_name):#constructor for FulltimeEmployee
        super().__init__(name,family,salary,department)
        self.c_name=c_name
    def setCompany(self,c_name):#one of the FulltimeEmployee class function
        self.c_name=c_name
    def getCompany(self):
        if self.c_name not in self.c_name:
            return ""
        return self.c_name
Nikhil=FulltimeEmployee("Nikhil","Vemula",100000,"Front-end","TCS")#FultimeEmployee object
Nikhil.setCompany("Meta")#calling the member functions of FulltimeEmploye and Employee
Nikhil.getCompany(),Nikhil.displayEmployee(),emp1.displayCount()

avg: 3500.0
Name :  Nikhil Family:  Vemula Salary:  100000 department: Front-end
Total Employee 3


('Meta', None, None)

In [5]:
import numpy as np

# Create a random vector of size 20 with float values in the range 1-20
random_vector = np.random.uniform(1, 10, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print("Random Vector:")
print(random_vector)

print("\nReshaped Array:")
print(reshaped_array)

Random Vector:
[0.         3.33122349 5.02472438 4.71792708 3.85763154 0.
 5.44242928 8.32652711 2.52128161 5.29878238 8.70917403 1.4481327
 7.69442439 0.         5.00937155 2.58554884 9.18614627 0.
 1.2830551  3.91732884]

Reshaped Array:
[[0.         3.33122349 5.02472438 4.71792708 3.85763154]
 [0.         5.44242928 8.32652711 2.52128161 5.29878238]
 [8.70917403 1.4481327  7.69442439 0.         5.00937155]
 [2.58554884 9.18614627 0.         1.2830551  3.91732884]]
